### ISSUE TITLE
using wordpress acf shortcods in tablepress goes outside the table

### ISSUE THREAD

**Issue by torpheh** [TobiasBg/TablePress#104]
I want to put some audio files in a html table using wordpress default [audio] shortcode and using ACF to take the url of song.
because of using two nested shortcode does not renderrd in wordpress, I have done this using a costume shortcode and a function.
and now this is my code:
`add_shortcode('audio_nested',custume_url_callback);`
`function custume_url_callback ($atts = ''){`
    `$value = shortcode_atts( array(`
      `  'my_feild' => '',`
  `  ), $atts );`
 `   $urlmusic = get_field($value['my_feild']);`
    `    echo do_shortcode("[audio src='$urlmusic']");`
`}`
now when I use it in the post contents it is OK, but when I use my shortcode in a table, the player does not appear in the table and goes on the top of post contents.
but if I use the default [audio src="XXX.mp3"] in the table it works good and will be placed right in the table cell.
I have tested the tablepress plugin. here you can see a screenshot of the problem:
https://pasteboard.co/HO9A2lw.png

**Comment by TobiasBg** [comment]
Hi @torpheh,

I don't really have an idea what's going on here, but it might be related to the audio Shortcode being somewhat special.
You could try turning off the TablePress output caching here, by changing the Shortcode to
`[table id=123 cache_table_output=false /]`

Alternatively, you could try using the direct PHP callback function for the audio Shortcode, instead of using `do_shortcode()`.

Regards,
Tobias

**Comment by torpheh** [comment]
@TobiasBg 
Thank you man, using wordpress php function directly instead of the sortcode answerd, and my problem is solved.
