### ISSUE TITLE
[Improvement] Please do NOT hide message "Table saved successfully" after a few seconds

### ISSUE THREAD

**Issue by SlashTray** [TobiasBg/TablePress#110]
Note: "Table saved successfully" may not be the exact message displayed in English (rough translation from French).

TablePress is the only WP extension I'm using that hides this kind of message after a few seconds. Bad idea! Anyone inattentive / suddenly busy elsewhere can easily forget if he/she has clicked "Save modifications" or NOT...

Please please please... keep this message displayed on screen until new modifications are made. Thank a lot in advance.

**Comment by TobiasBg** [comment]
Hi @SlashTray,

thanks for your post and feedback, I really appreciate it!

I have never looked at it this way, to be honest. I can't really believe that TablePress would be the only plugin doing this, and for normal tables, the saving process should be quite fast, so that the risk of missing the notification should be small. I will however add this to my list of ideas and if I can come up with a good way of implementing this, I'll happily give it a second look!

Thanks again for the suggestion!

Best wishes,
Tobias

**Comment by SlashTray** [comment]
Hi Tobias,
I'm not saying TablePress is the only one (out of tons of plugins), just that _among the few plugins I'm using_, TablePress is indeed the only one ;)
"The risk of missing the notification should be small" -> it depends... And my brain (memory) may not be working as well as it used to some decades ago... ;)
Thanks for having replied to my suggestion in any case.

**Comment by TobiasBg** [comment]
Hi,

I have now investigated this a bit and noticed that popular apps (like Slack for example) do it the same way. This makes me think that this is actually not too uncommon behavior?
Also, I don't think there's a big risk of missing to save, because before closing the browser tab or clicking a navigation link, you do get a warning by the browser if you have not saved.
But regardless, I will test a change for this for a future release! So, thanks again for the suggestion!

Regards,
Tobias

**Comment by SlashTray** [comment]
PlanSo Form Builder displays it "forever". As well as Events Manager (which also includes a "cross" to manually hide the message if desired).
Your message stays on screen for approximately 3 seconds, which is far too short IMO. Just raising the delay to 10-15 seconds would be enough.
