### ISSUE TITLE
DataTables Sorting plugin

### ISSUE THREAD

**Issue by milkotodorov** [TobiasBg/TablePress#120]
The plugin is not recognising the format dd.mmm.yyyy - example:
```
02.Jan.2009
01.Jun.2010
01.Feb.2009
```
Even  with number as month is still the same:
```
02.01.2009
01.06.2010
01.02.2009
```

**Comment by TobiasBg** [comment]
Hi @milkotodorov,

indeed, the first format that you mention is not supported. For that, you would need a custom algorithm or maybe use the approach from https://wordpress.org/support/topic/date-order-6/

The second format is however possible, you might just have to add the `date-eu` format definition manually via a "Custom Command".

Regards,
Tobias

**Comment by milkotodorov** [comment]
Thank you Tobias for the fast answer.
Adding the type as `date-eu` indeed works -> `"columnDefs": [ { "type": "formatted-num", "targets": [ 0 ] } ]`
However in your documentation on https://tablepress.org/extensions/datatables-sorting-plugins/ you documented the type as `formatted-num`.

**Comment by TobiasBg** [comment]
Hi,

yes, indeed, the `date-eu` time is not mentioned in the Documentation right now, I will have to add that.

No, not all plugins from https://datatables.net/plug-ins/sorting/ are available, only a few. For details, you will have to check out the JavaScript file in the TablePress Extension. This needs to be added separately, because these are indeed plugins for DataTables and not part of the normal file. If you want to use other or custom sorting algorithms, you could also add them to the JS files of the TablePress Extension.

Regards,
Tobias

**Comment by milkotodorov** [comment]
Thank you!
