### ISSUE TITLE
Optimize font loading techniques

### ISSUE THREAD

**Issue by martijn19811** [TobiasBg/TablePress#126]
Right now, the TablePress font is loaded in the website like this:

`@font-face {
    font-family: TablePress;
    src: url(//<SITE>/wp-content/plugins/tablepress/css/tablepress.eot);
    src: url(//<SITE>/wp-content/plugins/tablepress/css/tablepress.eot?#ie) format('embedded-opentype'),url(<LOTS OF CODE>) format('woff'),url(//<SITE>/wp-content/plugins/tablepress/css/tablepress.ttf) format('truetype'),url(//<SITE>/wp-content/plugins/tablepress/css/tablepress.svg#TablePress) format('svg');
    font-weight: 400;
    font-style: normal
}`

This can still massively be improved for a better PageSpeed score. Please add the following:

- Add `font-display: swap` to the font-face and make sure that wherever you use a font-family property declaring TablePress, a fallback like Arial will also be inserted
- Add woff2 and woff support. In fact, **the rest shouldn't be necessary anymore**, WOFF2 and WOFF2 will do fine nowadays: [https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/webfont-optimization?hl=nl](url)

**Comment by TobiasBg** [comment]
Hi @martijn19811,

thanks for opening this ticket! I'm not too familiar with font loading, can you maybe help me out with these questions?

- TablePress only uses the font to display the sorting and pagination arrow icons when the JS features for TablePress are turned on. Thus, they are not actual text, so that there's nothing to `swap` them with, and also no fallback font. Should I still add the CSS property?
- The woff format is including in that list (with inlined data, to avoid another HTTP request), is woff2 necessary then? And to the others harm if kept in the list? From what I know, they are not loaded, except when necessary, right?

Thanks!
Tobias

**Comment by martijn19811** [comment]
Ah Tobias,

excellent questions, thanks! And you're absolutely right. There's nothing to swap them with, my apologies. What you could be using is `font-display: block` (https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display). As there's nothing to swap, it'll briefly show nothing (more like invisible text) and then switch over to the icon set. Still an improvement over the default behavior :)

Nowadays, unless you still support IE8, only providing WOFF2 and WOFF is enough (https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/webfont-optimization). WOFF2 is lighter and therefore faster than WOFF. The rest is outdated, if I can be so blunt.

Hope I made all of this clear!

**Comment by TobiasBg** [comment]
Hi @martijn19811,

thanks for the clarification! That helps a lot!
I'll put this on the list for the next version!

Best wishes,
Tobias
