### ISSUE TITLE
Tablepress gets stuck in infinit loop when saving a imported table

### ISSUE THREAD

**Issue by ollpej** [TobiasBg/TablePress#128]
When I imported Excel and CSV files and hit the save button the process get takes saving. It isn't more then 15 rows and I'm hiding some of the 18 columns.
It goes so far with the saving process that the ISP temporary blocks my client IP to the server...
Some times the changed get applied.

Didn't have this issue before I started to import Excel files and the problem persist even after I have deleted those tables. (The deletes caused the same problem)

**Comment by TobiasBg** [comment]
Hi @ollpej,

That sounds strange, and I don't really see what could be going on there... Does this really only happen to imported tables, or also to tables (of the same size) that were created directly in TablePress?
It's even stranger that this continues after you deleted the tables again. For me, this indicates that this is likely a server or database problem, and not really a bug in TablePress (otherwise, I should also have received more reports about this).
Can you maybe try again after temporarily deactivating all other plugins and after switching to a WordPress default theme like Twenty Sixteen? This way, we can rule out interference from other plugins.

Regards,
Tobias

**Comment by TobiasBg** [comment]
Hi,

without further feedback, I'm not sure how I can help here.
I'll therefore close this issue for now. Please feel free to reopen it with more information, thanks!

Best wishes,
Tobias
