### ISSUE TITLE
Conflict using the Pagination Length Change “All” Entry plugin together with "language": {"lengthMenu": "_MENU_ custom_text"}

### ISSUE THREAD

**Issue by svenalbinus** [TobiasBg/TablePress#131]
First of all, if I use the plugin Pagination Length Change “All” Entry with changing the tablepress-length-change-all.php file in line 33 in

`$length_menu_values[] = '"Alle"';`

and everything work fine.

But if I use additionally custom commands like

`"language": {"lengthMenu": "_MENU_ custom_text"}` 

there is maybe a conflict and it shows only the numbers 10, 25, 50, 100 without 'All' or 'Alle'. If I delete the custom commands, it works fine again.

Have anybody I idea to fix it?

Best
Sven

**Comment by TobiasBg** [comment]
Hi @svenalbinus,

this is indeed a bit tricky, because of the object key `"lengthMenu"`, which is used in to places.
A quick fix could be to change the beginning of line 34 in the file tablepress-length-change-all.php from
`$parameters['lengthMenu'] = ...`
to
`$parameters['lengthMenuKey'] = ...`

Regards,
Tobias

**Comment by svenalbinus** [comment]
It works fantastic. Thx a lot. Have nice evening!
