### ISSUE TITLE
White page?

### ISSUE THREAD

**Issue by willnewby** [TobiasBg/TablePress#136]
Hello! 

First off, love the plugin. It works great and is super useful. 

I'm having an issue where if I load a table with 300+ rows, it loads a blank page. 

Here's what I've tried so far:
If I load the same dataset, but only 130 or so, it loads without issue.
If I load the full number of rows with fewer columns, it gives a white page.
If I preview the table or the page the table is on in Elementor, it works without issue. 

I'm testing with the following settings:
![image](https://user-images.githubusercontent.com/1313599/89250966-255eb180-d5d3-11ea-9a67-2124110b6d1e.png)

I've tested on a server with 8GB of RAM, and the amount of memory I give it doesn't seem to make a difference.
Any advice?

**Comment by TobiasBg** [comment]
Hi @willnewby,

to me, this does actually indicate that there's a PHP memory limit problem.

Could you maybe try increasing that by setting the `WP_MEMORY_LIMIT` constant in your site's wp-config.php to a higher values, like `512M`, via the instructions from https://wordpress.org/support/article/editing-wp-config-php/#increasing-memory-allocated-to-php? Please also make sure that you are using a modern version of PHP, like 7.3 or even 7.4, on the server, as these need much less memory than older versions.

If this does not help, we'll need to find out more about the actual error. For that, please set the `WP_DEBUG` constant to true in that file, via https://wordpress.org/support/article/editing-wp-config-php/#wp_debug. This should then give us some error messages to work with, instead of just a blank screen.

Regards,
Tobias

**Comment by willnewby** [comment]
Hi @TobiasBg , thanks for getting back to me so quickly!

Here's my current settings in `wp-config.php`
```
# WP Engine Settings
define('WP_MEMORY_LIMIT', '1024M');
define( 'WP_MAX_MEMORY_LIMIT', '2048M' );
ini_set('display_errors','On');
ini_set('error_reporting', E_ALL );

define('WP_DEBUG', true);
define( 'WP_DISABLE_FATAL_ERROR_HANDLER', true );   // 5.2 and later
define('WP_DEBUG_LOG', true);
define('WP_DEBUG_DISPLAY', true);
```
And no dice on an error message when I load the page, even after I purge caches.

I'm currently running on PHP 7.4 (on WPEngine, if that makes a difference).

**Comment by TobiasBg** [comment]
Hi @willnewby,

ok, that's interesting then... To be honest, I have no real clue what's going on then. Could you maybe check source code of the blank page (Right click and "View source" in the browser) to see if there was really nothing transferred from the server or if the output just stops in the middle?

Regards,
Tobias

**Comment by willnewby** [comment]
Hi @TobiasBg,

I'd love to, except that source of the page is really nothing. It seems I have to dig in more to even get a useful error! 

I'll re-open my issue if/when I find more.
Thanks for your help so far!
Will

**Comment by TobiasBg** [comment]
Hi,

what kind of HTTP response code do you get? Is the server software/firewall maybe blocking something?

Regards,
Tobias

**Comment by willnewby** [comment]
Here's what cURL gives me:
```
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 200
< server: nginx
< date: Tue, 04 Aug 2020 07:47:13 GMT
< content-type: text/html; charset=UTF-8
< content-length: 0
< x-powered-by: WP Engine
< x-pass-why: custom-path```

Here's a page that errors: https://dev.charterindustries.com/elementor-26185/
Here's one with a shorter table that works: https://dev.charterindustries.com/products/office-furniture-refurbishing/

**Comment by TobiasBg** [comment]
Hi,

ok, so for some reason nginx does seem to send anything here. I have no clue why though :-( Maybe the PHP fast-cgi is erroring or something? Unfortunately, this is beyond my level of expertise so that I can only suggest to have the host support team maybe take a look at the server error log files.

Regards,
Tobias

**Comment by mopquill** [comment]
Hi Tobias, I work with @willnewby! I did a bunch of debugging, and determined it to be a conflict with the WPMU's plugin, [Smush](https://wordpress.org/plugins/wp-smushit/) -- we have an image column in those tables, and Smush was doing... _something_ weird. We tried running with 8GB of RAM just for the heck of it, and there was nothing in the error log -- it was exiting cleanly with no output. And I purposefully overflowed the memory and verified that I got WordPress/error log errors -- I did.

Anyhow, we've just disabled Smush for now. Thanks for your help!

**Comment by TobiasBg** [comment]
Hi @mopquill,

thanks for the update on this! If you find anything that I can change in TablePress to make this work, just let me know!

Best wishes,
Tobias

**Comment by mopquill** [comment]
Hi @TobiasBg!

Nope, I think it's just a large amount of images on one page, and whatever Smush is doing. So with a table with a lot of rows (even if paginated, they're loaded), Smush seems to hit some cap and just `exit()` -- I didn't go through Smush's code to figure out why, that it was the culprit was a good enough answer for me. Thanks for making a great plugin, and cheers! 🍻
