### ISSUE TITLE
Have TablePress show pages a table is embedded on

### ISSUE THREAD

**Issue by filip-van-hoeckel** [TobiasBg/TablePress#151]
It's great that we can edit tables using the link in the frontend. It would be even better if we had a column indicating the page where tables are used in (like "attached" for Media). This way we can also remove tables that are no longer in use.

**Comment by TobiasBg** [comment]
Hi @filip-van-hoeckel,

thanks for this suggestion! Unfortunately, something like this is not really possible at the moment, due to how Shortcodes work in WordPress. Not only can they be embedded in very many places on a site (normal page/post content, sidebar widget, etc.) but tables can also be added via Template Tag functions or direct code. Due to that, it's just not reliably possible to determine where tables are shown. Thus, such a feature could lead to incomplete results and therefore a bad user experience.
Unless we can come up with ideas and solutions to make this really robust, I just don't see a way to implement something like this. Sorry for not having better news here.

Best wishes,
Tobias
