### ISSUE TITLE
Vanilla JS

### ISSUE THREAD

**Issue by moltra** [TobiasBg/TablePress#153]
Have you thought about changing from jQuery to vanilla JS?  With the new Google Core Vitals jQuery is penalized

**Comment by TobiasBg** [comment]
Hi @moltra,

thanks for your post! For the admin screens, I'm indeed already working on that. For the frontend (with the features like sorting, search, pagination, etc.), this will however not be possible yet, as TablePress uses the external DataTables JavaScript library for this, which currently still requires jQuery, see https://datatables.net/manual/installation#Dependencies.
Once DataTables no longer uses jQuery, I'll of course try to find a way to get rid of jQuery in the TablePress code as well.

Regards,
Tobias

**Comment by moltra** [comment]
Have you looked to see how hard it would be to use https://github.com/fiduswriter/Simple-DataTables in place of DataTabkea?

**Comment by TobiasBg** [comment]
Hi @moltra,

yes, I have seen this library, and it looks very promising. At this time, I can't directly replace DataTables with it, however, as it does not have all the features and is not a drop-in replacement. Due to the large number of TablePress users, this would cause a lot of trouble. Also, existing [TablePress Extensions](https://tablepress.org/extensions/) would break.

I'll however investigate if I can make this available as an Extension itself, so that users who would like to use this instead of DataTables can do so. I can't promise results in the near future here though.

Regards,
Tobias

**Comment by moltra** [comment]
I was just wondering, I am not a JavaScript programmer and was not sure

**Comment by TobiasBg** [comment]
Hi @moltra,

neither am I ;-)
Thanks again for the suggestion! Let's hope that this will be possible in the future!

Best wishes,
Tobias

**Comment by shaunroselt** [comment]
I'm using https://github.com/fiduswriter/Simple-DataTables and it's amazing. Would definitely recommend considering to use it instead of a JQuery alternative.

**Comment by TobiasBg** [comment]
Hi @shaunroselt,

thanks for the feedback here! This is still on my list of ideas for a TablePress Extension, but it's not a high priority, I'll be honest.

Regards,
Tobias
