### ISSUE TITLE
Tablepress custom css not working

### ISSUE THREAD

**Issue by itparkmallph** [TobiasBg/TablePress#154]
Hi Tobias, 

I'm having trouble changing the color header of the table. How do I change it?

**Comment by TobiasBg** [comment]
Hi @itparkmallph,

please see https://tablepress.org/faq/change-background-color-table-head-row/ for some "Custom CSS" code to change the table header colors. If that does not work, please post a link to the page with the table where this problem happens, so that I can take a direct look. Thanks!

Regards,
Tobias
