### ISSUE TITLE
Editor page hangs browser when table has many rows (~1000)

### ISSUE THREAD

**Issue by use** [TobiasBg/TablePress#162]
Hello,

I know this sounds ridiculous, but I use TablePress to import tables with over 2000 rows several times a year.

When going to the editor page, the browser hangs and shows the "this page is slowing your browser (wait/exit page)" dialog.

Once the initialization JS finishes (several minutes, if ever), everything works more-or-less like it would on a smaller table. So I think the performance bottleneck must be happening during the init process?

I would be happy to investigate this issue myself if there's perhaps a "developer getting started" guide?

**Comment by TobiasBg** [comment]
Hi @use,

Yes, this is a known issue. Essentially, the browser is running into memory issues due to the large amount of textareas on the page. I'm already working on completely rewriting the “Edit” screen with a different technical approach, that will make editing tables much faster, even for large tables. This will ship with TablePress 2.0, which I'm currently planning for the late second quarter.

In the meantime, my suggestion for handling large tables is to work on them offline (e.g. in Excel on an exported CSV file) and then re-import that file after making changes, choosing to replace the existing copy in TablePress.

Regards,
Tobias
