### ISSUE TITLE
Add: Visibility Status for whole Table

### ISSUE THREAD

**Issue by dertimm** [TobiasBg/TablePress#33]
Hi Tobias,
I love your plugin for its simplicity in usage for non-coder. Thank you for your work!

As we used it for a time now, there is a question I want to ask about a new, hopefully simple feature.
Like the In/Visible status for selected rows it would be great to have a same option in the "dashbord" for a whole table.
For Example it could look like:
    Edit | Shortcode | Copy | Export | Delete | **Visible** | Preview

and
        Edit | Shortcode | Copy | Export | Delete | **Invisible** | Preview

That would he helpful for having a site with two tables whereas one is only relevant and you could just switch the visibility of them.

**Comment by TobiasBg** [comment]
Hi @dertimm,

thanks for your suggestion! Unfortunately, I'll have to disappoint you on this at this time.
I don't have plans to add something like this to the plugin, and to be honest, I don't think that this will be useful to the majority of plugin users. In contrast, it might actually lead to confusion, when users accidentally activate this and then are confused that their tables are not showing.

Instead, I suggest to simply remove the Shortcode of the table from a page, if you don't want that table to be shown.
If this would be a lot of work (e.g. because you have added the same table on multiple pages), you could also use one of the available plugin filter hooks, to prevent that table with a certain ID is shown, e.g. the `tablepress_table_output` filter hook [here](https://github.com/TobiasBg/TablePress/blob/master/classes/class-render.php#L543).

Another idea could be to merge those two tables into one bigger one (given that the data in them "belongs together"), and then use the regular "Hide rows" feature to show only the relevant rows.

Best wishes,
Tobias
