### ISSUE TITLE
Can't get tables to display at 100% width

### ISSUE THREAD

**Issue by damian5000** [TobiasBg/TablePress#44]
They first load 100% width, but then revert to squashed after the page is fully loaded. Any ideas? Thanks much.

http://www.gizbeat.com/10100/19-available-now-and-upcoming-mediatek-marshmallow-android-phones/

· Website: http://www.gizbeat.com	
· TablePress: 1.7	
· TablePress (DB): 32	
· TablePress table scheme: 3	
· Plugin installed: 2013/03/11 18:53:22	
· WordPress: 4.5.2	
· Multisite: no	
· PHP: 5.4.41	
· mysqli Extension: false	
· mySQL (Server): 5.5.45-cll-lve	
· mySQL (Client): 5.5.45	
· ZIP support: yes	
· UTF-8 conversion: yes	
· WP Memory Limit: 40M	
· Server Memory Limit: 256M	
· Magic Quotes: off	
· WP_DEBUG: false	
· WP_POST_REVISIONS: true

**Comment by TobiasBg** [comment]
Hi @damian5000,

thanks for your post, and sorry for the trouble.

This is most likely caused by an issue with the Horizontal Scrolling, which seems to have a bug in the current version. As a workaround, I suggest to uncheck the "Use DataTables" checkbox on the table's "Edit" screen (as you are not using any other features at the moment), and instead use the `scroll` mode of the TablePress Extension from https://tablepress.org/extensions/responsive-tables/ which also adds horizontal scrolling, but in a more robust way (and without JavaScript).

Regards,
Tobias

**Comment by damian5000** [comment]
Okay Tobias. Thanks for your quick reply. It works. You can close this
ticket.

As an aside, might be cool to be able to bulk edit settings in all tables.
As opposed to having to go into each one and deselect "Use DataTables". And
maybe some way to bulk implement the plugin as opposed to opening and
editing each post...Though possible I can use some wildcard find/replace in
database to add responsive=scroll?

**Comment by TobiasBg** [comment]
Hi,

yes, some bulk editing could be a possibility. I'll have to investigate if there are good ways to implement this. For now, checking such find/replace for the Shortcode could be an option for you.

Best wishes,
Tobias
