### ISSUE TITLE
DataTables not available in preview

### ISSUE THREAD

**Issue by strarsis** [TobiasBg/TablePress#56]
In preview DataTables features are not available.
It makes sense to have this available in preview, too, 
because one can review and try out the changes by DataTables options.

**Comment by TobiasBg** [comment]
Hi,

yes, this would definitely make sense, but there are multiple things that have prevented that this could be added so far:
The Preview uses two modes for being loaded: One via an `<iframe>`, which should allow this. The other method however uses inline AJAX to then create the DOM elements on the fly. So far, I haven't been able to run JS commands with that however :-/
Also, the benefits (just as the plain Preview now) are somewhat limited anyways, due to the CSS styling of the theme and other plugins not being taken into account. So, the best approach here might actually be to rewrite the Preview so that it uses an actual frontend request so that all relevant CSS/JS files are loaded. This could potentially result in integration in the Customizer, but I don't have plans or ideas on how to implement that yet.

Regards,
Tobias
