### ISSUE TITLE
colgroups filter/support

### ISSUE THREAD

**Issue by strarsis** [TobiasBg/TablePress#57]
There is a `tablepress_print_colgroup_tag` filter (for <colgroup>s) but apparently no GUI feature yet for controlling it.

**Comment by TobiasBg** [comment]
Yes, this is by design. I think that the `colgroup` HTML tag is by far one of the least used things in HTML tables. I actually don't remember any support questions for this at the moment.
Therefore, a GUI for this would probably confuse more users than it would help. I'd rather keep the UI simple and offer such rarely used things via filters.
