### ISSUE TITLE
Injecting jQuery

### ISSUE THREAD

**Issue by stirtingale** [TobiasBg/TablePress#61]
The plugin has the ability to toggle css on/off

However, I have un-enqueued Jquery on my site (and have it loaded in a minified grunt-generated file). TablePress, however, reinjects jQuery v1.12.4 immediately before jquery.datatables.min.js?ver=1.8

This causes a conflict on my site and blocks Stripe from loading. 

Can jQuery be toggled on/off or an option to unhook from the functions.php be added?

**Comment by TobiasBg** [comment]
Thanks for your post, and sorry for the trouble. TablePress needs jQuery (specifically, the DataTables JS library needs jQuery). Now, the JS code is quite stable so that TablePress does not load the jquery-migrate.js script, which is part of the default jQuery loading of WordPress.
It does so, by enqueuing the handle `jquery-core`, so all that might be necessary is for you to extend your dequeue code to also dequeue the `jquery-core` script handle.

**Comment by stirtingale** [comment]
Yep - "wp_deregister_script('jquery-core');" works to remove it.

It also removes the dataTable js (but that can be bundled in with the other vendor scripts)

Thanks for the speedy reply

**Comment by TobiasBg** [comment]
That's good to hear! Yes, this might also cause WordPress to no longer load DataTables, as one of its dependencies is not loaded.

The better approach might therefore ultimately be to fix whatever script is failed when the original jQuery library is loaded. Usually, this is just a matter of replacing the `$` shortcut with `jQuery` in that script.

**Comment by stirtingale** [comment]
Ordinarily, I would - in this case, my client was relying on an AWS hosted script to push Stripe payments through to a third-party CRM. Sadly I can't edit that and Payments trump tables :)
