### ISSUE TITLE
Hooks before import

### ISSUE THREAD

**Issue by Nks** [TobiasBg/TablePress#66]
Hey.
I already wrote in the wordpress support theme.
Just repeating this here.

The problem in using invalid markup in the HTML files which provided by another system and problem can’t be done without modification $temp_data in the class-import.php (line 158). Each time when I uploading the file with the invalid markup libxml will return an error (and this is okay) but this will be much more powerful if we will modify the ```$temp_data``` before starting working with it in the next step. Something like ```$temp_data = apply_filters('tablepress_html_import_temp_data', $temp_data);``` will be enough I think.

**Comment by TobiasBg** [comment]
Hi @Nks,

thanks for opening this issue and submitting the PR! This would definitely make sense! I think I was reluctant to add filters to not make the import library dependent on WordPress (so that it could potentially be used in other projects), but I think this is not really necessary.

So, yes, having these hooks is a good idea, and I will gladly add them. I'm a bit busy at the moment, but I'll add them in my next round of development!

Thanks again!
Tobias

**Comment by TobiasBg** [comment]
Hi @Nks,

this has finally been added in https://github.com/TobiasBg/TablePress/commit/e65d094e9f32c8593077a83909c59db06120ada7 :-)

Note that I opted to only add one global filter hook. Choosing the import format is possible via the `$format` parameter.

Thanks for your contribution!
Tobias
