### ISSUE TITLE
I can't autoupdate table using url 

### ISSUE THREAD

**Issue by iamkanp** [TobiasBg/TablePress#70]
I can't autoupdate table using url  with json format.  Please let me know how to diagnose the case.
showing "Failed @ date time" in column Last Auto Import thank you @TobiasBg

**Comment by TobiasBg** [comment]
Hi @iamkanp,

thanks for your post, and sorry for the trouble.

Does the import from that URL in JSON format work with a manual import (i.e. on the "Import" screen)?
Does everything work with e.g. a CSV file?

Note that TablePress can only import its own JSON format, but no arbitrary JSON formats. Can you therefore maybe give me the URL of the file that you are trying to import?

Regards,
Tobias

**Comment by iamkanp** [comment]
Hi @TobiasBg ,
        Could you send me your email (my email is iamkanp@hotmail.com)? i will give you that url. Sorry for inconvinience
        I try it manually. it works and also, i just create a php file that echo the json. it works as well.
        just failed when getting from url directly. Is there any problem with time delay when the server querying data?
Regards,
Kan P.

**Comment by TobiasBg** [comment]
Hi @iamkanp,

thanks for the link! I have tested your URL on my site (with the manual import), and that is working fine. The JSON format is correct, too.

Because of that, I can only assume that your server is not properly connecting to the URL, for some reason. One reason might be that it's a Punycode/internationalized domain, or that it takes quite a while for the URL to return the content.
Unfortunately, finding out the exact cause is beyond what I can help with here, as the issue very likely is on the server level :-(

Regards,
Tobias

**Comment by iamkanp** [comment]
Dear @Tobias Bäthge<mailto:tobias@baethge.com>

        Thanks for your try. However, could you tell me what is the differences between

           1.  the first import by url (i can use my link with your plugin even it's take a 10-20 seconds waiting.)

           2.  your autoupdate period by url (showing : Failed)

        is it the same command to import ? and can set up any delay time? and if i want to analyse the problem, can i use log in chorme dev.?



        However, if it can't use with my url. If i write a .php script to write a static file on server and then let you extension to read periodically, is it possible?

        Or, do you have any more idea to use autoupdate with my url link.

Thank you so much,

Kan P.

________________________________

**Comment by TobiasBg** [comment]
Hi,

yes, it's the same code for the import. However, there are same differences in the background, that could play a role. For example, as the auto import uses the WP Cron feature, it runs as a non-logged-in user in WordPress. This could result in different parameters being used, for things like memory limit or HTTP requests. The developer tools in Chrome will not help with this, you would have to directly add debugging/testing to the PHP file of the Extension. Then, instead of relying on the cron job to run, you could use plugins like https://wordpress.org/plugins/core-control/ to manually run the import cron job.

Now, trying the auto import with a direct file import (from the server) could of course also work, but you would have to test it (first with a static file maybe).

Of course, if your PHP script runs on the same server as the WordPress installation, and if it has access to the database, you could directly update the data in the database.

Regards,
Tobias

**Comment by iamkanp** [comment]
Thanks a lot

Sent from Kan's iPhone

On 20 Nov BE 2560, at 01:34, Tobias Bäthge <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

yes, it's the same code for the import. However, there are same differences in the background, that could play a role. For example, as the auto import uses the WP Cron feature, it runs as a non-logged-in user in WordPress. This could result in different parameters being used, for things like memory limit or HTTP requests. The developer tools in Chrome will not help with this, you would have to directly add debugging/testing to the PHP file of the Extension. Then, instead of relying on the cron job to run, you could use plugins like https://wordpress.org/plugins/core-control/ to manually run the import cron job.

Now, trying the auto import with a direct file import (from the server) could of course also work, but you would have to test it (first with a static file maybe).

Of course, if your PHP script runs on the same server as the WordPress installation, and if it has access to the database, you could directly update the data in the database.

Regards,
Tobias

**Comment by TobiasBg** [comment]
Hi @iamkanp,

any new findings here?

Regards,
Tobias

**Comment by iamkanp** [comment]
Thanks for asking me my progress
Now i create files on server instead
It work ti read files on server thanks

Sent from Kan's iPhone

On 27 Nov BE 2560, at 17:14, Tobias Bäthge <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @iamkanp<https://github.com/iamkanp>,

any new findings here?

Regards,
Tobias
