### ISSUE TITLE
Table data clone alignment issue

### ISSUE THREAD

**Issue by house-johanlindqvist** [TobiasBg/TablePress#84]
There is an alignment issue in our case that causes the rows to not align properly. Anyone else experienced similar issue? And if so. How did you resolve it?

You can see the issue on this page: https://www.catenamedia.com/investors/key-performance-indicators-definitions/

Thanks.

**Comment by TobiasBg** [comment]
Hi @house-johanlindqvist,

from what I can see, all this is caused by additional CSS and JavaScript code that your theme (or maybe another plugin) loads.

Can you therefore please try again after temporarily deactivating all other plugins and after switching to a WordPress default theme like Twenty Sixteen? That way, we can find what's causing this.

Best wishes,
Tobias

**Comment by house-johanlindqvist** [comment]
Thanks for your quick reply. Seems like you are right. Thanks for your help!
