### ISSUE TITLE
Responsive collapse

### ISSUE THREAD

**Issue by gmarink** [TobiasBg/TablePress#85]
Is it possible to choose which columns will be cut to run in responsive collapse mode?

**Comment by TobiasBg** [comment]
Hi @gmarink,

Unfortunately, I’m not too familiar with this (because it relates to the external DataTables JS library) and can only suggest taking a look at the examples like https://wordpress.org/support/topic/defining-columns-to-collapse-1?replies=12 or https://wordpress.org/support/topic/collapse-extension-breaking-point?replies=6

Regards,
Tobias

**Comment by shariq02ca** [comment]
Hey Tobias,

I am also trying to figure this one out. 

An example would be. 
https://10beasts.com/best-wireless-earbuds/

In the aforementioned website, on a mobile you can see the column 2 and 3 are collapsed whereas we can see column 0, 1, and 4.

I tried following your examples but since I am not a coder really struggling with it.

Any help would be well appreciated.

Best Regards,
Shaq
